version: '3'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./share:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    restart: unless-stopped

